// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockmatrix.proto

package blkstorage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Contains information about the block matrix ledger such as size, block count, and row/column hashes.
type BlockmatrixInfo struct {
	Size                 uint64   `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	BlockCount           uint64   `protobuf:"varint,2,opt,name=blockCount,proto3" json:"blockCount,omitempty"`
	RowHashes            [][]byte `protobuf:"bytes,3,rep,name=rowHashes,proto3" json:"rowHashes,omitempty"`
	ColumnHashes         [][]byte `protobuf:"bytes,4,rep,name=columnHashes,proto3" json:"columnHashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockmatrixInfo) Reset()         { *m = BlockmatrixInfo{} }
func (m *BlockmatrixInfo) String() string { return proto.CompactTextString(m) }
func (*BlockmatrixInfo) ProtoMessage()    {}
func (*BlockmatrixInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f05697675af98205, []int{0}
}

func (m *BlockmatrixInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockmatrixInfo.Unmarshal(m, b)
}
func (m *BlockmatrixInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockmatrixInfo.Marshal(b, m, deterministic)
}
func (m *BlockmatrixInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockmatrixInfo.Merge(m, src)
}
func (m *BlockmatrixInfo) XXX_Size() int {
	return xxx_messageInfo_BlockmatrixInfo.Size(m)
}
func (m *BlockmatrixInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockmatrixInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlockmatrixInfo proto.InternalMessageInfo

func (m *BlockmatrixInfo) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *BlockmatrixInfo) GetBlockCount() uint64 {
	if m != nil {
		return m.BlockCount
	}
	return 0
}

func (m *BlockmatrixInfo) GetRowHashes() [][]byte {
	if m != nil {
		return m.RowHashes
	}
	return nil
}

func (m *BlockmatrixInfo) GetColumnHashes() [][]byte {
	if m != nil {
		return m.ColumnHashes
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockmatrixInfo)(nil), "blkstorage.BlockmatrixInfo")
}

func init() { proto.RegisterFile("blockmatrix.proto", fileDescriptor_f05697675af98205) }

var fileDescriptor_f05697675af98205 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xca, 0xc9, 0x4f,
	0xce, 0xce, 0x4d, 0x2c, 0x29, 0xca, 0xac, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a,
	0xca, 0xc9, 0x2e, 0x2e, 0xc9, 0x2f, 0x4a, 0x4c, 0x4f, 0x55, 0x6a, 0x67, 0xe4, 0xe2, 0x77, 0x42,
	0xa8, 0xf0, 0xcc, 0x4b, 0xcb, 0x17, 0x12, 0xe2, 0x62, 0x29, 0xce, 0xac, 0x4a, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x09, 0x02, 0xb3, 0x85, 0xe4, 0xb8, 0xb8, 0xc0, 0x06, 0x39, 0xe7, 0x97, 0xe6,
	0x95, 0x48, 0x30, 0x81, 0x65, 0x90, 0x44, 0x84, 0x64, 0xb8, 0x38, 0x8b, 0xf2, 0xcb, 0x3d, 0x12,
	0x8b, 0x33, 0x52, 0x8b, 0x25, 0x98, 0x15, 0x98, 0x35, 0x78, 0x82, 0x10, 0x02, 0x42, 0x4a, 0x5c,
	0x3c, 0xc9, 0xf9, 0x39, 0xa5, 0xb9, 0x79, 0x50, 0x05, 0x2c, 0x60, 0x05, 0x28, 0x62, 0x4e, 0x16,
	0x51, 0x66, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0x19, 0x95, 0x05,
	0xa9, 0x45, 0x39, 0xa9, 0x29, 0xe9, 0xa9, 0x45, 0xfa, 0x69, 0x89, 0x49, 0x45, 0x99, 0xc9, 0xfa,
	0xc9, 0xf9, 0xb9, 0xb9, 0xf9, 0x79, 0xfa, 0x50, 0x41, 0x84, 0x1f, 0x92, 0xd8, 0xc0, 0xde, 0x32,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xca, 0x17, 0x05, 0xc7, 0xeb, 0x00, 0x00, 0x00,
}
