// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	"github.com/hyperledger/fabric/common/ledger"
	cluster "github.com/hyperledger/fabric/orderer/common/cluster"

	mock "github.com/stretchr/testify/mock"
)

// LedgerFactory is an autogenerated mock type for the LedgerFactory type
type LedgerFactory struct {
	mock.Mock
}

// GetOrCreate provides a mock function with given fields: chainID, lt
func (_m *LedgerFactory) GetOrCreate(chainID string, lt ledger.Type) (cluster.LedgerWriter, error) {
	ret := _m.Called(chainID, lt)

	var r0 cluster.LedgerWriter
	if rf, ok := ret.Get(0).(func(string, ledger.Type) cluster.LedgerWriter); ok {
		r0 = rf(chainID, lt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cluster.LedgerWriter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, ledger.Type) error); ok {
		r1 = rf(chainID, lt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
