// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	common "github.com/hyperledger/fabric-protos-go/common"
	ledger "github.com/hyperledger/fabric/common/ledger"

	mock "github.com/stretchr/testify/mock"
)

// ChainReplicator is an autogenerated mock type for the ChainReplicator type
type ChainReplicator struct {
	mock.Mock
}

// ReplicateChains provides a mock function with given fields: lastConfigBlock, chains
func (_m *ChainReplicator) ReplicateChains(lastConfigBlock *common.Block, chains map[string]ledger.Type) []string {
	ret := _m.Called(lastConfigBlock, chains)

	var r0 []string
	if rf, ok := ret.Get(0).(func(*common.Block, map[string]ledger.Type) []string); ok {
		r0 = rf(lastConfigBlock, chains)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
