// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger_metadata.proto

package msgs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Status specifies the status of a ledger
type Status int32

const (
	Status_ACTIVE             Status = 0
	Status_INACTIVE           Status = 1
	Status_UNDER_CONSTRUCTION Status = 2
)

var Status_name = map[int32]string{
	0: "ACTIVE",
	1: "INACTIVE",
	2: "UNDER_CONSTRUCTION",
}

var Status_value = map[string]int32{
	"ACTIVE":             0,
	"INACTIVE":           1,
	"UNDER_CONSTRUCTION": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8173a53a47b026a1, []int{0}
}

type LedgerType int32

const (
	LedgerType_Blockchain  LedgerType = 0
	LedgerType_Blockmatrix LedgerType = 1
)

var LedgerType_name = map[int32]string{
	0: "Blockchain",
	1: "Blockmatrix",
}

var LedgerType_value = map[string]int32{
	"Blockchain":  0,
	"Blockmatrix": 1,
}

func (x LedgerType) String() string {
	return proto.EnumName(LedgerType_name, int32(x))
}

func (LedgerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8173a53a47b026a1, []int{1}
}

// BootSnapshotMetadata captures the metadata of the snapshot that was used to bootstrap the ledger
type BootSnapshotMetadata struct {
	SingableMetadata     string   `protobuf:"bytes,1,opt,name=singableMetadata,proto3" json:"singableMetadata,omitempty"`
	AdditionalMetadata   string   `protobuf:"bytes,2,opt,name=additionalMetadata,proto3" json:"additionalMetadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootSnapshotMetadata) Reset()         { *m = BootSnapshotMetadata{} }
func (m *BootSnapshotMetadata) String() string { return proto.CompactTextString(m) }
func (*BootSnapshotMetadata) ProtoMessage()    {}
func (*BootSnapshotMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_8173a53a47b026a1, []int{0}
}

func (m *BootSnapshotMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootSnapshotMetadata.Unmarshal(m, b)
}
func (m *BootSnapshotMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootSnapshotMetadata.Marshal(b, m, deterministic)
}
func (m *BootSnapshotMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootSnapshotMetadata.Merge(m, src)
}
func (m *BootSnapshotMetadata) XXX_Size() int {
	return xxx_messageInfo_BootSnapshotMetadata.Size(m)
}
func (m *BootSnapshotMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BootSnapshotMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BootSnapshotMetadata proto.InternalMessageInfo

func (m *BootSnapshotMetadata) GetSingableMetadata() string {
	if m != nil {
		return m.SingableMetadata
	}
	return ""
}

func (m *BootSnapshotMetadata) GetAdditionalMetadata() string {
	if m != nil {
		return m.AdditionalMetadata
	}
	return ""
}

// LedgerMetadata specifies the metadata of a ledger
type LedgerMetadata struct {
	Status               Status                `protobuf:"varint,1,opt,name=status,proto3,enum=msgs.Status" json:"status,omitempty"`
	BootSnapshotMetadata *BootSnapshotMetadata `protobuf:"bytes,2,opt,name=boot_snapshot_metadata,json=bootSnapshotMetadata,proto3" json:"boot_snapshot_metadata,omitempty"`
	LedgerType           LedgerType            `protobuf:"varint,3,opt,name=ledgerType,proto3,enum=msgs.LedgerType" json:"ledgerType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LedgerMetadata) Reset()         { *m = LedgerMetadata{} }
func (m *LedgerMetadata) String() string { return proto.CompactTextString(m) }
func (*LedgerMetadata) ProtoMessage()    {}
func (*LedgerMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_8173a53a47b026a1, []int{1}
}

func (m *LedgerMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LedgerMetadata.Unmarshal(m, b)
}
func (m *LedgerMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LedgerMetadata.Marshal(b, m, deterministic)
}
func (m *LedgerMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LedgerMetadata.Merge(m, src)
}
func (m *LedgerMetadata) XXX_Size() int {
	return xxx_messageInfo_LedgerMetadata.Size(m)
}
func (m *LedgerMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_LedgerMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_LedgerMetadata proto.InternalMessageInfo

func (m *LedgerMetadata) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_ACTIVE
}

func (m *LedgerMetadata) GetBootSnapshotMetadata() *BootSnapshotMetadata {
	if m != nil {
		return m.BootSnapshotMetadata
	}
	return nil
}

func (m *LedgerMetadata) GetLedgerType() LedgerType {
	if m != nil {
		return m.LedgerType
	}
	return LedgerType_Blockchain
}

func init() {
	proto.RegisterEnum("msgs.Status", Status_name, Status_value)
	proto.RegisterEnum("msgs.LedgerType", LedgerType_name, LedgerType_value)
	proto.RegisterType((*BootSnapshotMetadata)(nil), "msgs.BootSnapshotMetadata")
	proto.RegisterType((*LedgerMetadata)(nil), "msgs.LedgerMetadata")
}

func init() { proto.RegisterFile("ledger_metadata.proto", fileDescriptor_8173a53a47b026a1) }

var fileDescriptor_8173a53a47b026a1 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4f, 0xfa, 0x30,
	0x14, 0xc7, 0x19, 0xbf, 0x5f, 0x16, 0x7d, 0x10, 0x5c, 0x1a, 0x24, 0xc4, 0x93, 0x21, 0x1e, 0x0c,
	0x89, 0x9b, 0xc1, 0x83, 0xd1, 0x9b, 0x20, 0x07, 0x12, 0x1c, 0x66, 0x0c, 0x0f, 0x5e, 0x48, 0xbb,
	0xd5, 0xad, 0x61, 0x5b, 0x97, 0xb6, 0x18, 0xf9, 0xd7, 0xfc, 0xeb, 0x0c, 0x5d, 0x9d, 0x26, 0x72,
	0xeb, 0xfb, 0xbe, 0x6f, 0xdf, 0xfb, 0x7c, 0x5b, 0x38, 0xcd, 0x68, 0x9c, 0x50, 0xb1, 0xce, 0xa9,
	0xc2, 0x31, 0x56, 0xd8, 0x2d, 0x05, 0x57, 0x1c, 0xfd, 0xcf, 0x65, 0x22, 0x07, 0x02, 0xba, 0x63,
	0xce, 0xd5, 0xb2, 0xc0, 0xa5, 0x4c, 0xb9, 0x7a, 0x32, 0x1e, 0x34, 0x04, 0x47, 0xb2, 0x22, 0xc1,
	0x24, 0xa3, 0xdf, 0x5a, 0xdf, 0x3a, 0xb7, 0x2e, 0x8f, 0x83, 0x3f, 0x3a, 0x72, 0x01, 0xe1, 0x38,
	0x66, 0x8a, 0xf1, 0x02, 0x67, 0xb5, 0xbb, 0xa9, 0xdd, 0x07, 0x3a, 0x83, 0x4f, 0x0b, 0x3a, 0x73,
	0xcd, 0x54, 0x8f, 0xb8, 0x00, 0x5b, 0x2a, 0xac, 0xb6, 0x52, 0x2f, 0xe9, 0x8c, 0xda, 0xee, 0x9e,
	0xce, 0x5d, 0x6a, 0x2d, 0x30, 0x3d, 0xf4, 0x0c, 0x3d, 0xc2, 0xb9, 0x5a, 0x4b, 0x43, 0x5b, 0x47,
	0xd2, 0xcb, 0x5a, 0xa3, 0xb3, 0xea, 0xd6, 0xa1, 0x40, 0x41, 0x97, 0x1c, 0x8a, 0x79, 0x0d, 0x50,
	0xbd, 0x4e, 0xb8, 0x2b, 0x69, 0xff, 0x9f, 0xde, 0xed, 0x54, 0x53, 0xe6, 0xb5, 0x1e, 0xfc, 0xf2,
	0x0c, 0xef, 0xc1, 0xae, 0xa8, 0x10, 0x80, 0xfd, 0x30, 0x09, 0x67, 0x2f, 0x53, 0xa7, 0x81, 0xda,
	0x70, 0x34, 0xf3, 0x4d, 0x65, 0xa1, 0x1e, 0xa0, 0x95, 0xff, 0x38, 0x0d, 0xd6, 0x93, 0x85, 0xbf,
	0x0c, 0x83, 0xd5, 0x24, 0x9c, 0x2d, 0x7c, 0xa7, 0x39, 0xbc, 0x02, 0xf8, 0x99, 0x8a, 0x3a, 0x00,
	0xe3, 0x8c, 0x47, 0x9b, 0x28, 0xc5, 0xac, 0x70, 0x1a, 0xe8, 0x04, 0x5a, 0xba, 0xce, 0xb1, 0x12,
	0xec, 0xc3, 0xb1, 0xc6, 0x77, 0xaf, 0xb7, 0x09, 0x53, 0xe9, 0x96, 0xb8, 0x11, 0xcf, 0xbd, 0x74,
	0x57, 0x52, 0x51, 0x81, 0x78, 0x6f, 0x98, 0x08, 0x16, 0x79, 0x11, 0x17, 0xd4, 0x33, 0xd2, 0xe6,
	0xdd, 0x1c, 0xf6, 0xf0, 0xc4, 0xd6, 0x7f, 0x7c, 0xf3, 0x15, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x03,
	0x08, 0xc5, 0xfc, 0x01, 0x00, 0x00,
}
