// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockmatrix.proto

package blockmatrix

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Contains information about the block matrix ledger such as size, block count, and row/column hashes.
type Info struct {
	Size                 uint64   `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	BlockCount           uint64   `protobuf:"varint,2,opt,name=blockCount,proto3" json:"blockCount,omitempty"`
	RowHashes            [][]byte `protobuf:"bytes,3,rep,name=rowHashes,proto3" json:"rowHashes,omitempty"`
	ColumnHashes         [][]byte `protobuf:"bytes,4,rep,name=columnHashes,proto3" json:"columnHashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_f05697675af98205, []int{0}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Info) GetBlockCount() uint64 {
	if m != nil {
		return m.BlockCount
	}
	return 0
}

func (m *Info) GetRowHashes() [][]byte {
	if m != nil {
		return m.RowHashes
	}
	return nil
}

func (m *Info) GetColumnHashes() [][]byte {
	if m != nil {
		return m.ColumnHashes
	}
	return nil
}

func init() {
	proto.RegisterType((*Info)(nil), "blkstorage.Info")
}

func init() { proto.RegisterFile("blockmatrix.proto", fileDescriptor_f05697675af98205) }

var fileDescriptor_f05697675af98205 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xcf, 0xbf, 0x6b, 0x85, 0x30,
	0x10, 0x07, 0x70, 0xac, 0xa1, 0xd0, 0xc3, 0xa5, 0x99, 0x1c, 0x4a, 0x11, 0x27, 0x27, 0x33, 0xf4,
	0x3f, 0xb0, 0x1d, 0xda, 0xd5, 0xb1, 0x5b, 0x92, 0x17, 0x35, 0x98, 0xe4, 0x24, 0x89, 0xbc, 0x1f,
	0xbc, 0x3f, 0xfe, 0x41, 0x10, 0xf4, 0x6d, 0xc7, 0xe7, 0xbe, 0x07, 0xf7, 0x85, 0x77, 0x61, 0x50,
	0xce, 0x96, 0x47, 0xaf, 0x2f, 0xed, 0xe2, 0x31, 0x22, 0x05, 0x61, 0xe6, 0x10, 0xd1, 0xf3, 0x51,
	0xd5, 0x77, 0x20, 0x7f, 0x6e, 0x40, 0x4a, 0x81, 0x04, 0x7d, 0x53, 0x65, 0x56, 0x65, 0x0d, 0xe9,
	0xd3, 0x4c, 0x3f, 0x01, 0xd2, 0xf1, 0x37, 0xae, 0x2e, 0x96, 0x2f, 0x69, 0x73, 0x10, 0xfa, 0x01,
	0x6f, 0x1e, 0xcf, 0xbf, 0x3c, 0x4c, 0x2a, 0x94, 0x79, 0x95, 0x37, 0x45, 0xbf, 0x03, 0xad, 0xa1,
	0x90, 0x68, 0x56, 0xeb, 0xb6, 0x00, 0x49, 0x81, 0x27, 0xeb, 0x7e, 0xfe, 0xbb, 0x51, 0xc7, 0x69,
	0x15, 0xad, 0x44, 0xcb, 0xa6, 0xeb, 0xa2, 0xbc, 0x51, 0xa7, 0x51, 0x79, 0x36, 0x70, 0xe1, 0xb5,
	0x64, 0x12, 0xad, 0x45, 0xc7, 0x36, 0xdc, 0xff, 0x66, 0x87, 0x56, 0xe2, 0x35, 0xd5, 0xfa, 0x7a,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xec, 0x6b, 0x3e, 0xeb, 0x00, 0x00, 0x00,
}
